import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase-admin';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function GET(request) {
  // Validate Vercel CRON authorization
  const authHeader = request.headers.get('authorization');
  if (
    process.env.NODE_ENV === 'production' &&
    authHeader !== `Bearer ${process.env.CRON_SECRET}`
  ) {
    return new Response('Unauthorized', { status: 401 });
  }

  try {
    // 1. Calculate the time range (last 24 hours)
    const now = new Date();
    const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);

    // 2. Fetch orders within the last 24 hours
    const { data: orders, error } = await supabaseAdmin
      .from('orders')
      .select(`
        id,
        created_at,
        total_amount,
        status,
        customer_name,
        session_id,
        table_sessions (
          table_id,
          tables ( name )
        ),
        order_items (
          quantity,
          menu_items ( name )
        )
      `)
      .gte('created_at', yesterday.toISOString())
      .order('created_at', { ascending: false });

    if (error) throw error;

    // 3. Compute Metrics
    const totalOrders = orders.length;
    const totalRevenue = orders.reduce((sum, order) => sum + Number(order.total_amount || 0), 0);
    
    const dineInOrders = orders.filter(o => o.table_sessions?.tables?.name && !['Takeaway', 'Delivery', 'Online'].includes(o.table_sessions.tables.name));
    const onlineOrders = orders.filter(o => o.table_sessions?.tables?.name && ['Takeaway', 'Delivery', 'Online'].includes(o.table_sessions.tables.name));

    // 4. Generate HTML Report
    const htmlContent = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #E8730E;">Nagpal Sweets & Namkeen - Daily Report</h2>
        <p>Here is your summary for <strong>${yesterday.toLocaleDateString()} to ${now.toLocaleDateString()}</strong>:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background: #f9f9f9;"><strong>Total Revenue</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd; font-size: 1.2em; color: #22c55e;"><strong>₹${totalRevenue}</strong></td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background: #f9f9f9;"><strong>Total Orders</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${totalOrders}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background: #f9f9f9;"><strong>Dine-in Orders</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${dineInOrders.length}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #ddd; background: #f9f9f9;"><strong>Online Orders</strong></td>
            <td style="padding: 10px; border: 1px solid #ddd;">${onlineOrders.length}</td>
          </tr>
        </table>

        <h3>Recent Order Details</h3>
        ${orders.length > 0 ? `
          <table style="width: 100%; border-collapse: collapse; font-size: 0.9em;">
            <thead>
              <tr style="background: #f1f1f1;">
                <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Time</th>
                <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Table/Type</th>
                <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Items</th>
                <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${orders.map(o => `
                <tr>
                  <td style="padding: 8px; border: 1px solid #ddd;">${new Date(o.created_at).toLocaleTimeString()}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${o.table_sessions?.tables?.name || 'Unknown'}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">
                    ${o.order_items?.map(i => `${i.quantity}x ${i.menu_items?.name}`).join('<br>')}
                  </td>
                  <td style="padding: 8px; border: 1px solid #ddd;">₹${o.total_amount}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        ` : '<p>No orders were placed today.</p>'}
        
        <p style="margin-top: 30px; font-size: 0.8em; color: #666;">
          This is an automated report generated by your Nagpal Sweets & Namkeen ordering system.
        </p>
      </div>
    `;

    // 5. Send Email via Resend
    // By default on Resend free tier, you can only send from onboarding@resend.dev to your verified email
    const { data, error: resendError } = await resend.emails.send({
      from: 'Nagpal Sweets <onboarding@resend.dev>',
      to: [process.env.ADMIN_EMAIL],
      subject: `Daily Report: ₹${totalRevenue} (${now.toLocaleDateString()})`,
      html: htmlContent,
    });

    if (resendError) {
      console.error('Resend Error:', resendError);
      return NextResponse.json({ error: resendError }, { status: 500 });
    }

    return NextResponse.json({ success: true, data });

  } catch (error) {
    console.error('Cron job error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
